### ISSUE TITLE
accuracy of form factors

### ISSUE THREAD

**Issue by claudeha** [kdudka/rrv#4]
The current FormFactorEngine calculation of hemicube pixel form factors seems suspect to me after reading this (see pages 5 and 6): http://artis.imag.fr/Members/Cyril.Soler/DEA/IlluminationGlobale/Papers/p31-cohen.pdf

**Comment by kdudka** [comment]
Thank you for opening the issue!  Is this going to be fixed by your patchset at https://github.com/kdudka/rrv/commits/claude ?

**Comment by claudeha** [comment]
yes - commit https://github.com/kdudka/rrv/commit/d9b85ef8e0f8ef05133a80c74f4f245b4920f098 adds the calculations and commit https://github.com/kdudka/rrv/commit/b7d2a4474431bfdbc99943931519c14b0271f844 makes it the default, both are in your patchset

(apologies for delay, life got in the way)

**Comment by kdudka** [comment]
Thank you for fixing it!  Closing as resolved...
