### ISSUE TITLE
Dependencies

### ISSUE THREAD

**Issue by stolk** [kdudka/rrv#6]
The README doesn't list them, so you may want to add the dependencies.
(I dont think cmake is looking for them, so you will only find out with build errors.)

Depends on libglfw3-dev
Depends on libglm-dev

**Comment by kdudka** [comment]
To be honest, I did not know that rrv depends on ```glfw``` and ```glm```.  If it is really the case, we should add them to both ```CMakeLists.txt``` and ```README```.  Any idea if they are needed on non-Linux platforms, too?

**Comment by stolk** [comment]
rrv-compute-gl3 uses glfw unconditionally, so yeah, that would be for all platforms that are intended to build rrv-compute-gl3

Same for glm

```
# Executable binary rrv-compute-gl3
add_executable(rrv-compute-gl3
    rrv-compute-gl3.cpp)
target_link_libraries(rrv-compute-gl3 rrv -lGLEW -lglfw -fopenmp)
```

**Comment by kdudka** [comment]
Thank you for clarifying it!  I have pushed a check for the dependencies at configure time.  Then I realized that ```README``` does not document dependencies at all so I had nothing to update actually :-/
